# Generated by Django 4.1.2 on 2022-12-15 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_enseignant_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='libele',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='cours',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='cours'),
        ),
    ]
