# Generated by Django 4.1.2 on 2022-12-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_cours_libele_cours_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='thumbnail',
            new_name='coursthumbnail',
        ),
        migrations.RemoveField(
            model_name='cours',
            name='enseignant',
        ),
        migrations.AddField(
            model_name='cours',
            name='prof',
            field=models.CharField(choices=[('Lana', 'Lana'), ('Antonio', 'Antonio'), ('Brandon', 'Brandon')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='cours',
            name='profimage',
            field=models.ImageField(blank=True, null=True, upload_to='enseignants'),
        ),
        migrations.DeleteModel(
            name='Enseignant',
        ),
    ]
