# Generated by Django 4.1.2 on 2022-12-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_thumbnail_cours_coursthumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='price',
            field=models.IntegerField(default=50.0),
        ),
    ]
