# Generated by Django 4.1.2 on 2022-12-28 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cours_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cours', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.cours')),
            ],
        ),
    ]
