# Generated by Django 4.1.2 on 2022-12-29 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('Lana', 'Lana'), ('Antonio', 'Antonio'), ('Brandon', 'Brandon')], default='', max_length=50)),
                ('profimage', models.ImageField(blank=True, null=True, upload_to='enseignants')),
                ('description', models.TextField(max_length=1000)),
                ('fontion', models.TextField(max_length=500)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cours')),
            ],
        ),
    ]
