# Generated by Django 4.1.2 on 2022-12-29 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_cours_prof_remove_formateur_cours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formateur',
            name='onIndex',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
